### ISSUE TITLE
Can you share examples where this was needded and/or applied?

### ISSUE THREAD

**Issue by naugtur** [qnighy/node-cjs-interop#2]
I'm working on a runtime that could support __esModule out of the box or keep the node.js behavior. Trying to figure out which one is more likely to cause trouble.  
Can you share examples of npm packages that need/use node-cjs-interop?  
Maybe add a short case study to the readme too?

**Comment by qnighy** [comment]
I'm not sure if you are still working on it, but here are some examples I know of: qhistory, react-textarea-autosize, redux-thunk, and styled-components.
