### ISSUE TITLE
[SWC] Missing export __get_transform_plugin_core_pkg_diagfailed to invoke plugin

### ISSUE THREAD

**Issue by SettingDust** [qnighy/node-cjs-interop#43]
```
Caused by:
    Missing export __get_transform_plugin_core_pkg_diagfailed to invoke plugin: failed to invoke plugin on 'Some("src/index.ts")'
```
```
"experimental": {
  "plugins": [
    ["swc-plugin-node-cjs-interop", {
      "packages": ["ts-deepmerge"]
    }]
  ]
}
```

**Comment by qnighy** [comment]
Thank you for the report. What version of SWC are you using?

**Comment by SettingDust** [comment]
"@swc/core": "^1.3.14",

**Comment by qnighy** [comment]
I have updated SWC dependencies. As this is likely some sort of version incompatibility, I'll go ahead and close this issue for now. Feel free to reopen or file another issue if you observe similar issues after the upgrade.
